config/routes.rb
Rails.application.routes.draw do
 
	root 'home#index'

	get '/home/:id', to: 'home#item'

	get 'wel/admin'
	get 'wel/announcement1'
	get 'wel/announcement2'
	get 'wel/announcement3'
	
	get 'cart/add'
	get 'cart/shop'
	
	resources :products
	resources :orders
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	validates :id, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
	validates :id, presence: true
end

app/models/temp.rb
class  Temp < Object
	def initialize(amount,product)
		@amount = amount
		@id = product.id
		@title = product.title
		@item = product.item
		@price = product.price
		@remark = product.remark
	end
	
	def amount
		return @amount
	end
	def id
		return @id
	end
	def title
		return @title
	end
	def item
		return @item
	end
	def price
		return @price
	end
	def remark
		return @remark
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
  
	protected
	def fetch_home_data
		if cookies[:shop_cart].blank?
			@shopping_cart_count = 0
		else
			@shopping_cart_count = JSON.parse(cookies[:shop_cart]).size
		end
	end
  
	def cparm
		@all_st = [["XA科",1], ["XB科", 2], ["XC科",3], ["XD科",4], ["XE科",5],
				["XF科",6], ["XG站",7], ["XH科",8], ["XI科",9], ["XJ科",10], 
				["XK科",11], ["XL科",12], ["XM科",13], ["XN科",14], ["XO科",15], 
				["XP科",16], ["XQ科",17]]
		@all_ad = [["已废弃",0],["未确认",1], ["已确认", 2], ["已下单",3], ["已收货",4], ["完成",5]]
		@all_item = [["硒鼓墨盒",1], ["电脑配件", 2], ["办公纸笔",3], ["办公文具",4], ["财务用品",5], ["其他",6]]
	end
	
	def order_notice
		@lists = ["没有新的订单信息1", "没有新的订单信息2", "没有新的订单信息3", "没有新的订单信息4",
				"没有新的订单信息5", "没有新的订单信息6", "没有新的订单信息7", "没有新的订单信息8"]
		@num = 0
	end
	
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  def add
	fetch_home_data
	
	@pid = (params[:non].to_i/100).to_i
	@pno = params[:non].to_i%100
    @product = Product.find(@pid)
  end
  
  def shop
	fetch_home_data
	cparm
	
	if cookies[:shop_cart].blank?
		@arr = nil
	else
		@arr = JSON.parse(cookies[:shop_cart])
	end
	
	if(params[:non]!=nil)
		@arr.each do |item|
			if (item/100).to_i.to_s==params[:non]
				@arr.delete item
			end
		end
		cookies[:shop_cart]=@arr.to_json
	end
	
	unless @arr.blank?
		@product = Array.new
		@arr.sort!
		@arr.each do |item|
			pid = (item/100).to_i
			pno = item%100
			tenp = Temp.new(pno,Product.find(pid))
			@product.push tenp
		end
	end
	
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
	fetch_home_data
	order_notice
  end
  
  def item
	fetch_home_data
	order_notice
	cparm
	
	@item = params[:id]
	@title = @all_item[@item.to_i-1][0]
	
	@products = Product.where("item = '#{params[:id]}'")
  end
  

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
	
	http_basic_authenticate_with name: "denghan", password: "linshigong", except: [:create, :show]
	protect_from_forgery :only => [:create]
	
	def index
		@orders = Order.all
	end
	
	def new
		cparm
		@order = Order.new
	end
	
	def create
		fetch_home_data
	
#		render plain: params[:order].inspect#
		
		@order = Order.new(order_params)
		
		@order.id = (@order.id+1)*1000 + Order.count + 1
		
		if @order.save
			redirect_to @order
		else
			render 'new'
		end
	end
	
	def edit
		cparm
		@order = Order.find(params[:id])
	end
	
	def show
		fetch_home_data
		cparm
		@order = Order.find(params[:id])
		@stage = @all_ad[@order.stage-1][0]
		
		@item = @all_st[@order.secke-1][0]
		@time = '20'+String(@order.id)[0]+String(@order.id)[1]+"年"+String(@order.id)[2]+
		String(@order.id)[3]+"月"+String(@order.id)[4]+String(@order.id)[5]+"日"
		
		@product = Array.new
		@amount = Array.new
		@order.list.split(pattern=',').each{|x|
			pid = (x.to_i/100).to_i
			pno = (x.to_i%100).to_i
			
			@product.push(Product.find(pid))
			@amount.push(pno)
		}
	end
	
	def update
		@order = Order.find(params[:id])
		if @order.update(order_params)
			redirect_to @order
		else
			render 'edit'
		end
	end
	
	def destroy
		@order = Order.find(params[:id])
		@order.destroy
		
		redirect_to orders_path
	end
	
	private
		def order_params
			params.require(:order).permit(:id,:time,:secke,:stage,:list)
		end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

	http_basic_authenticate_with name: "denghan", password: "linshigong", except: [:show]
	
	def index
		@products = Product.all
	end
	
	def new
		cparm
		@product = Product.new
	end
	
	def create
#		render plain: params[:product].inspect#
		@product = Product.new(product_params)
		if @product.save
			redirect_to @product
		else
			render 'new'
		end
	end
	
	def edit
		cparm
		@product = Product.find(params[:id])
	end
	
	def show
		fetch_home_data
		order_notice
		cparm
		
		@product = Product.find(params[:id])
		@title = @all_item[@product.item-1][0]
	end
	
	def update
		@product = Product.find(params[:id])
		if @product.update(product_params)
			redirect_to @product
		else
			render 'edit'
		end
	end
	
	def destroy
		@product = Product.find(params[:id])
		@product.destroy
		
		redirect_to products_path
	end
	
	private
		def product_params
			params.require(:product).permit(:id,:title,:item,:price,:remark)
		end
end

app/controllers/wel_controller.rb
class WelController < ApplicationController

  def admin
  	fetch_home_data
	order_notice
  end

  def announcement1
  	fetch_home_data
	order_notice
  end

  def announcement2
  	fetch_home_data
	order_notice
  end

  def announcement3
  	fetch_home_data
	order_notice
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def show_add_to_cart product, options = {}
    html_class = "btn btn-danger add-to-cart-btn"
    html_class += " #{options[:html_class]}" unless options[:html_class].blank?
#
    link_to "<i class='fa fa-spinner'></i> 加入购物车".html_safe, cart_add_path(:non=>product), class: html_class
  end

  def current_cart
	if cookies[:shop_cart].blank?
		return nil
	else
		return JSON.parse(cookies[:shop_cart])
	end
  end
  
  def clear_cart
	cookies[:shop_cart] = nil
  end
  
  def add_to_cart(id)
	pid = (id/100).to_i
	pno = id%100
	if current_cart.blank?
		arr = Array.new
		arr.push id
	else
		arr = current_cart
		if arr.find{|item| (item/100).to_i==pid}.blank?
			item = id
			arr.push item
		else
			arr.collect!{|item|
				if (item/100).to_i==pid
					item = item+pno
					if item%100>=10
						item = pid*100+10
					end
				end
				item
			}
		end
	end
	cookies[:shop_cart]=arr.to_json
  end
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/wel_helper.rb
module WelHelper
end

app/views/cart/add.html.erb
<div class="row">
	<div class="container">
		<h4 class="text text-success"><i class='fa fa-check-circle-o'></i> 加入购物车成功!</h4>
		<% add_to_cart @pid*100+@pno %>
		<div class="alert alert-info">
			<div class="media shopping-cart-row">
				<div class="media-left">
					<%= image_tag "product/#{@product.id}.jpg", class: 'media-object', alt: @product.title, size: "100x100" %>
				</div>
				<div class="media-body"><br />
					<h3 class="media-heading"><%= @product.title %></h3>
					<p>库存&nbsp;:&nbsp;充足&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					单价:&nbsp;¥&nbsp;<%= @product.price %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
					数量:&nbsp;¥&nbsp;<%= @pno %></p>
				</div>
			</div>
		</div>
		<div class="pull-right">
			<strong><%= link_to "继续购物", :back %>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp</strong>
			<%= link_to "查看购物车", cart_shop_path, class: "btn btn-danger" %>
		</div>
    </div>
</div>

app/views/cart/shop.html.erb
<% content_for :head do%>
<%= javascript_include_tag 'cartshop', 'data-turbolinks-track': 'reload' %>
<% end %>


<h1>购物车</h1>
<div class="row">
  <div class="container">
    <div class="alert alert-info">
      <% unless @arr.blank? %>
        <% @product.each do |shopping_cart| %>
          <div class="media shopping-cart-row">
            <div class="media-left">
              <a href="<%= product_path(shopping_cart.id) %>">
			    <%= image_tag "product/#{shopping_cart.id}.jpg", alt: shopping_cart.title, size: "50x50" %>
              </a>
            </div>
            <div class="media-body">
				<h4 class="media-heading"><%= link_to shopping_cart.title, product_path(shopping_cart.id) %></h4>
				<span class="pid"><%= shopping_cart.id %></span>库存:充足&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
				单价: ¥<span class="price"><%= shopping_cart.price %></span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<button class="bleft" >&nbsp;-&nbsp;</button>
				<input type="text" value="<%= shopping_cart.amount %>" class="amount" />
				<button class="bright" >&nbsp;+&nbsp;</button>
				&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
				<strong>　　小计: </strong>
				<strong class="subtotle"></strong>
			</div>

            <div class="media-right">
				<br />
                <%= link_to "　删 除　", cart_shop_path(:non=>shopping_cart.id), class: "btn btn-default btn-xs" %>
            </div>
			<br />
          </div>
        <% end -%>
      <% else %>
        <h3>购物车为空</h3>
      <% end -%>
    </div>

    <% unless @arr.blank? %>
		<div class="row">
			<div class="col-md-2">
				<h4>请选择您的科室</h4>
				<%= select_tag(:lang, options_for_select(@all_st) , class: "form-control" ) %>
			</div>
			<div class="col-md-8"></div>
			<div class="col-md-2">
				<h3>总价: ¥<span class="totle">没算出来 !-_-　</span>　</h3>
				<button class="btn btn-danger btn-lg" id="cartorder">去结算</button>
			</div>
		</div>
		<div class="clearfix"></div>
    <% end %>
  </div>
</div>

app/views/home/_cagetable.html.erb
<ul class="list-group">
	<li class="list-group-item"><a href="/home/1">硒鼓墨盒</a></li>
	<li class="list-group-item"><a href="/home/2">电脑配件</a></li>
	<li class="list-group-item"><a href="/home/3">办公纸笔</a></li>
	<li class="list-group-item"><a href="/home/4">办公文具</a></li>
	<li class="list-group-item"><a href="/home/5">财务用品</a></li>
	<li class="list-group-item"><a href="/home/6">其他</a></li>
</ul>
<br />
<h3><strong>订单公告</strong></h3>
<br />
<ul class="list-group">
	<% for i in 0..7 %>
		<p><%= @lists[(i+@num)%8] %></p>
	<% end %>
</ul>

app/views/home/index.html.erb
<% content_for :head do%>
<%= javascript_include_tag 'index', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="row">
	<div class="col-lg-3">
		<%= render 'cagetable' %>
	</div>
	<div class="col-lg-9">
		<ol class="breadcrumb">
			<li class="active">Home</li>
		</ol>
		
		<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="5000">
			<ol class="carousel-indicators">
				<li data-target="#carousel-ad" data-slide-to="0" class="active"></li>
				<li data-target="#carousel-ad" data-slide-to="1"></li>
				<li data-target="#carousel-ad" data-slide-to="2"></li>
			</ol>
			<div class="carousel-inner" role="listbox">
				<div class="item active">
					<%= link_to image_tag("home/1.jpg", alt: "welcome"), wel_announcement1_path %>
				</div>
				<div class="item">
					<%= link_to image_tag("home/2.jpg", alt: "readme"), wel_announcement2_path %>
				</div>
				<div class="item">
					<%= link_to image_tag("home/3.jpg", alt: "whynot"), wel_announcement3_path %>
				</div>
			</div>
			<!-- 轮播（Carousel）导航 -->
			<a class="carousel-control left" href="#myCarousel"  data-slide="prev">&lsaquo;</a>
			<a class="carousel-control right" href="#myCarousel"  data-slide="next">&rsaquo;</a>
		</div>
	</div> 
</div>

app/views/home/item.html.erb
<div class="row">
	<div class="col-lg-3">
	<%= render 'cagetable' %>
	</div>
	<div class="col-lg-9">
		<ol class="breadcrumb">
			<li class="active">Home</li>
			<li class="active"><%= @title %></li>
		</ol>
		<div class="row">
			<% @products.each do |product| %>
				<div class="col-sm-6 col-md-4">
					<div class="thumbnail">
						<%= link_to image_tag("product/#{product.id}.jpg", alt: product.title), product_path(product) %>
						<div class="caption">
							<h4><%= link_to product.title, product_path(product), class: 'title' %></h4>
							
						</div>
						<div class="captionl">
							<h4><strong>¥<%= product.price %></strong></h4>
						</div>
						<div class="captionr">
							<%= show_add_to_cart product.id*100+1, html_class: "btn-xs" %></p>
						</div>
					</div>
				</div>
			<% end -%>
		</div>
	</div>
</div>

app/views/html/_101.html.erb
<div>
<h4>适用于P1007/P1008/P1106/P1108/M1136/M1213nf/M1216nfh</h4>
<%= link_to image_tag "tmp/101_1.jpg" %>
<%= link_to image_tag "tmp/101_2.jpg" %>
<%= link_to image_tag "tmp/101_3.gif" %>
<%= link_to image_tag "tmp/101_4.jpg" %>
<%= link_to image_tag "tmp/101_5.jpg" %>
<%= link_to image_tag "tmp/101_6.jpg" %>
<%= link_to image_tag "tmp/101_7.jpg" %>
</div>

app/views/layouts/_footer.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active">Probation Period</li>
      </ul>
	    <ul class="nav navbar-nav navbar-right">
        <li>Cocyright by Hann.Dent Tel:629000</li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">XX支队物资采购中心</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="<%= root_path %>">Home<span class="sr-only">(current)</span></a></li>
      </ul>
	    <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "购物车 (#{@shopping_cart_count})", action: :shop, controller: :cart %></li>
		    <li><%= link_to "管理员入口", action: :admin, controller: :wel %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html  lang="zh">
  <head>
    <title>采购中心</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
	<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<%= yield :head %>
  </head>
  <body>
    <%= render 'layouts/menu' %>
    <div class="container">
      <% unless flash[:notice].blank? %>
        <div class="alert alert-info"><%= flash[:notice] %></div>
      <% end -%>
      
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for @order do |f| %>
	<% if @order.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluraliza(@order.errors.count,"error") %>prohibited this order from being saved:
			</h2>
			<ul>
				<% @order.errors.full_message.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :id %><br>
		<%= f.text_field :id %>
	</p>
	<p>
		<%= f.label :time %><br>
		<%= f.text_field :time %>
	</p>
	<p>
		<%= f.label :secke %><br>
		<%= f.select :secke, options_for_select(@all_st) %>
	</p>
	<p>
		<%= f.label :stage %><br>
		<%= f.select :stage, options_for_select(@all_ad) %>
	</p>
	<p>
		<%= f.label :list %><br>
		<%= f.text_area :list %>
	</p>
	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/orders/edit.html.erb
<h1>Edit Order</h1>
<%= render 'form' %>
<%= link_to 'Back',orders_path %>

app/views/orders/index.html.erb
<% content_for :head do%>
<%= javascript_include_tag 'orderindex', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li class="active"><a href="/home/admin">管理员</a></li>
			<li class="active">订单处理</li>
		</ol>
		<%= link_to 'New order',new_order_path %>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>id</th><th>time</th><th>secke</th><th>stage</th><th>list</th><th>显示</th><th>编辑</th><th>删除</th>
				</tr>
			</thead>
			<tbody>
				<% @orders.each do |order| %>
				<tr>
					<td><%= order.id %></td>
					<td><%= order.time %></td>
					<td><%= order.secke %></td>
					<td class="color"><%= order.stage %></td>
					<td><%= order.list %></td>
					<td><%= link_to 'Show',order_path(order) %></td>
					<td><%= link_to 'Edit',edit_order_path(order) %></td>
					<td><%= link_to 'Destroy',order_path(order),method: :delete %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>	
</div>

app/views/orders/new.html.erb
<h1>New Order</h1>
<%= render 'form' %>
<%= link_to 'Back',orders_path %>

app/views/orders/show.html.erb
<% content_for :head do%>
<%= javascript_include_tag 'ordershow', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="row" >
	<div class="pull-left">
		<h3>当前订单状态：<span class:"stage"><%= @stage %></span></h3>
    </div>
	<div class="pull-right">
		<button class="btn btn-danger btn-lg" id="print">打 印</button>
    </div>
</div>
<% clear_cart %>
<br /><br />
<!--startprint-->
<div class="container" style="width:756px;height:1100px;">
	<div class="row" >
		<div class="col-xs-4">
		</div>
		<div class="col-xs-4">
			<h2>物资请领报告单</h2>
		</div>
		<div class="col-xs-4">
		</div>
	</div>
	<br />
	<div class="row" >
		<div class="pull-left">
			<p>订单编号：<%= @order.id %></p>
		</div>
		<div class="pull-right">
			<p>填制日期：<%= @time %></p>
		</div>
		<table class="table table-bordered">
			<thead>
				<tr>
					<th>序号</th>
					<th>商品类别</th>
					<th>商品编号</th>
					<th>商品名称</th>
					<th>数量</th>
					<th>单价</th>
					<th>小计</th>
					<th>备注</th>
				</tr>
			</thead>
			<tbody align="center">
				<% for i in 0..22 %>
					<% if i<@product.length %>
						<tr class="body">
							<td style="width:7%"><%= i+1 %></td>
							<td style="width:12%"><%= @all_item[@product[i].item-1][0] %></td>
							<td style="width:12%"><%= @product[i].id %></td>
							<td style="width:37%" align="left"><%= @product[i].title %></td>
							<td style="width:7%"><span class="amount"><%= @amount[i] %></span></td>
							<td style="width:8%"><span class="price"><%= @product[i].price %></span></td>
							<td style="width:9%"><span class="subtotle"></span></td>
							<td style="width:8%"></td>
						</tr>
					<% else %>
						<tr>
							<td style="width:7%"><%= i+1 %></td>
							<td style="width:12%"></td>
							<td style="width:12%"></td>
							<td style="width:37%"></td>
							<td style="width:7%"></td>
							<td style="width:8%"></td>
							<td style="width:9%"></td>
							<td style="width:8%"></td>
						</tr>
					<% end %>
				<% end %>
				<tr>
					<td style="width:7%">备注</td>
					<td colspan="3" style="width:61%" align="left">订单打印完成后经部门领导和经办人签字交与物资采购办公室确认订单，集中采购，收货后请及时领取，验收人签字后完成行政消耗采购。</td>
					<td style="width:7%">合计</td>
					<td style="width:8%"><span class="totle"><%= @order.time %></span></td>
					<td colspan="2" style="width:17%"><span class="bigtotle"><%= @order.time %></span></td>
				</tr>
			</tbody>
		</table>
	<div>
	<div class="row" >
		<div class="col-xs-4">
			<h4>部门领导审批：</h4>
		</div>
		<div class="col-xs-3">
			<h4>编制单位：<%= @item %></h4>
		</div>
		<div class="col-xs-2">
			<h4>经办人：</h4>
		</div>
		<div class="col-xs-3">
			<h4>验收人：</h4>
		</div>
	</div>
</div>
<!--endprint-->
<br /><br />

app/views/products/_form.html.erb
<%= form_for @product do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluraliza(@product.errors.count,"error") %>prohibited this product from being saved:
			</h2>
			<ul>
				<% @product.errors.full_message.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<p>
		<%= f.label :id %><br>
		<%= f.text_field :id %>
	</p>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :item %><br>
		<%= f.select :item, options_for_select(@all_item) %>
	</p>
	<p>
		<%= f.label :price %><br>
		<%= f.text_field :price %>
	</p>
	<p>
		<%= f.label :remark %><br>
		<%= f.text_area :remark %>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>
<%= render 'form' %>
<%= link_to 'Back',products_path %>

app/views/products/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li class="active"><a href="/home/admin">管理员</a></li>
			<li class="active">商品处理</li>
		</ol>
		<%= link_to 'New product',new_product_path %>
		<table class="table table-striped">
			<thead>
				<tr>
					<th>image</th><th>id</th><th>title</th><th>item</th><th>price</th><th>remark</th><th>显示</th><th>编辑</th><th>删除</th>
				</tr>
			</thead>
			<tbody>
				<% @products.each do |product| %>
				<tr>
					<td><%= image_tag "product/#{product.id}.jpg", alt: product.title, size: "50x50" %></td>
					<td><%= product.id %></td>
					<td><%= product.title %></td>
					<td><%= product.item %></td>
					<td><%= product.price %></td>
					<td><%= product.remark %></td>
					<td><%= link_to 'Show',product_path(product) %></td>
					<td><%= link_to 'Edit',edit_product_path(product) %></td>
					<td><%= link_to 'Destroy',product_path(product),method: :delete %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= render 'form' %>
<%= link_to 'Back',products_path %>

app/views/products/show.html.erb
<% content_for :head do%>
<%= javascript_include_tag 'productshow', 'data-turbolinks-track': 'reload' %>
<% end %>

<div class="row">
	<div class="col-lg-3">
		<%= render 'home/cagetable' %>
	</div>
	<div class="col-lg-9">
		<ol class="breadcrumb">
			<li class="active">Home</li>
			<li class="active"><%= @title %></li>
			<li class="active"><%= @product.title %></li>
		</ol>
		<h1><%= @product.title %></h1>
		<div class="row">
			<div class="col-xs-6 col-md-3">
				<%= link_to image_tag("product/#{@product.id}.jpg", alt: @product.title), "product/#{@product.id}.jpg" %>
			</div>
		</div>

		<ul class="list-unstyled">
			<li>商品编号: <span id="pid"><%= @product.id %></span></li>
			<li>库存: 充足</li>
		</ul>
		<h3><strong>¥<%= @product.price %></strong></h3>
		
		<div>
			<button class="bleft" >&nbsp;-&nbsp;</button>
			<input type="text" value="1" class="amount">
			<button class="bright" >&nbsp;+&nbsp;</button>
			<br />
			<br />
			<button class="btn btn-danger" id="addcart">加入购物车</button>
		</div>
		<br />
		<ul class="nav nav-tabs">
			<li role="presentation" class="active"><a href="javascript:;">商品描述</a></li>
		</ul>
		<br />
		<div>
			<% if @product.remark=="html" %>
				<%= render "html/#{@product.id}" %>
			<% else %>
				<%= @product.remark %>
			<% end %>
		</div>
		<br /><br /><br />
	</div>
</div>

app/views/wel/admin.html.erb
<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li class="active"><a href="/home/admin">管理员</a></li>
		</ol>
		
		<%= link_to "商品处理", products_path, class: "btn btn-danger" %>
		<%= link_to "订单处理", orders_path, class: "btn btn-danger" %>
	</div> 
</div>

app/views/wel/announcement1.html.erb
<div class="row">
	<div class="col-lg-12">
		
	</div> 
</div>

app/views/wel/announcement2.html.erb
<div class="row">
	<div class="col-lg-12">
		
	</div> 
</div>

app/views/wel/announcement3.html.erb
<div class="row">
	<div class="col-lg-12">
		
	</div> 
</div>